"""Intraday execution on a measured volume curve.

    python run_intraday.py

`engine/execution.py` states its own limit: "There is no intraday scheduling ...
The horizon is days and the unit is one day's volume." This is the intraday
half, built on 60 days of real 5-minute bars rather than an assumed U-shape --
assuming the curve and then demonstrating consequences of the assumption would
make the conclusion a property of the assumption.

Writes docs/INTRADAY.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from engine.intraday import (AUCTION_BUCKETS, CACHE, build, completion_curve,
                             curve_dispersion, load_profile, timing_exposure,
                             twap_vs_vwap)

DAILY_VOLUME = 50_000_000


def main() -> int:
    if not CACHE.exists():
        print("data/intraday_5m.parquet not found -- run fetch_intraday.py")
        return 1

    import pandas as pd

    prof = load_profile()
    disp = curve_dispersion(prof)
    raw = pd.read_parquet(CACHE)

    L = []
    add = L.append
    add("# ML-2 — intraday execution, on a curve that was measured")
    add("")
    add("Generated by `run_intraday.py` from {:,} real 5-minute bars across".format(
        len(raw)))
    add("{} names, {} to {}.".format(
        raw.ticker.nunique(), raw.index.min().date(), raw.index.max().date()))
    add("")
    add("`engine/execution.py` states its own limit: *there is no intraday")
    add("scheduling ... the horizon is days and the unit is one day's volume.*")
    add("This is the intraday half. The first decision was **not to assume the")
    add("shape of the day** — assuming a U and then demonstrating consequences")
    add("of the assumption makes the conclusion a property of the assumption.")
    add("")

    add("## 1. The measured day")
    add("")
    top = prof.sort_values(ascending=False).head(5)
    bot = prof.sort_values().head(3)
    add("| bucket | share of the day | vs uniform |")
    add("|---|---|---|")
    for t, v in top.items():
        add("| {}{} | {:.2%} | {:.1f}x |".format(
            t, " *(auction)*" if t in AUCTION_BUCKETS else "",
            v, v / disp["uniform_share"]))
    add("| ... | | |")
    for t, v in bot.items():
        add("| {} | {:.2%} | {:.2f}x |".format(t, v, v / disp["uniform_share"]))
    add("")
    add("| | |")
    add("|---|---|")
    add("| five-minute buckets in a session | {} |".format(disp["buckets"]))
    add("| busiest / quietest | **{:.1f}x** |".format(disp["max_over_min"]))
    add("| effective buckets (1/Herfindahl) | {:.1f} |".format(
        disp["effective_buckets"]))
    add("")
    add("The last row is the compact statement: {} buckets of clock time behave".format(
        disp["buckets"]))
    add("like **{:.0f}** buckets of liquidity. The day is roughly half as long".format(
        disp["effective_buckets"]))
    add("as it looks.")
    add("")
    add("The profile is computed as a share WITHIN each ticker-day and then")
    add("averaged, not as total volume per bucket over total volume. Summing raw")
    add("volume would let the busiest name and the busiest days dominate, so the")
    add("curve would describe SPY on a heavy week rather than a typical day.")
    add("")

    add("## 2. A stated participation rate is wrong at every interval")
    add("")
    add("*\"We traded at 5% of volume\"* is a statement about the day. A TWAP")
    add("schedule — equal quantity per slice, the obvious default — holds the")
    add("QUANTITY constant while the volume under it swings {:.0f}-fold.".format(
        disp["max_over_min"]))
    add("")
    add("| stated rate | TWAP worst interval | overshoot | VWAP worst interval |")
    add("|---|---|---|---|")
    for rate in (0.01, 0.05, 0.10):
        r = twap_vs_vwap(prof, DAILY_VOLUME * rate, DAILY_VOLUME)
        add("| {:.0%} | {:.1%} | **{:.1f}x** | {:.1%} |".format(
            rate, r["twap_max_participation"], r["twap_overshoot_ratio"],
            r["vwap_max_participation"]))
    add("")
    add("A compliance limit written as *never exceed 10% of volume* is breached")
    add("by a TWAP schedule whose daily average is 5%. The aggregate number is")
    add("true and every interval disagrees with it.")
    add("")

    add("## 3. What that costs")
    add("")
    add("Impact is driven by participation, not by quantity, and the engine's")
    add("square-root law makes cost per slice go as `sqrt(participation)`. A")
    add("schedule that concentrates participation into the thinnest part of the")
    add("day pays more than its average rate suggests.")
    add("")
    add("| stated rate | TWAP | VWAP | excess |")
    add("|---|---|---|---|")
    excesses = []
    for rate in (0.01, 0.05, 0.10, 0.20):
        r = twap_vs_vwap(prof, DAILY_VOLUME * rate, DAILY_VOLUME)
        excesses.append(r["excess_pct"])
        add("| {:.0%} | {:.2f} bp | {:.2f} bp | **{:+.1f}%** |".format(
            rate, r["twap_impact_bps"], r["vwap_impact_bps"], r["excess_pct"]))
    add("")
    add("**The penalty is identical at every size — {:.1f}% — and that is a".format(
        excesses[0]))
    add("check rather than a coincidence.** Under a square-root law the ratio")
    add("between two schedules is a pure function of the CURVE and cancels the")
    add("order size entirely. If it ever varied with size, the impact weighting")
    add("would be wrong. A test pins it.")
    add("")

    add("## 4. A claim this refuted about its own design")
    add("")
    add("The textbook cost of VWAP is that it **defers** execution: tracking the")
    add("volume curve pushes the order into the close, leaving the remainder")
    add("exposed to timing risk for longer — the same trade `execution.py`")
    add("prices over days. This document asserted that before measuring it.")
    add("")
    tw = build(prof, DAILY_VOLUME * 0.05, DAILY_VOLUME, "twap")
    vw = build(prof, DAILY_VOLUME * 0.05, DAILY_VOLUME, "vwap")
    ct, cv = completion_curve(tw, prof), completion_curve(vw, prof)
    add("| | TWAP | VWAP |")
    add("|---|---|---|")
    add("| timing exposure (avg fraction outstanding) | {:.4f} | **{:.4f}** |".format(
        timing_exposure(tw, prof), timing_exposure(vw, prof)))
    add("| complete by 12:00 | {:.1%} | **{:.1%}** |".format(
        ct["12:00"], cv["12:00"]))
    add("| complete by 15:00 | {:.1%} | {:.1%} |".format(
        ct["15:00"], cv["15:00"]))
    add("")
    add("**VWAP is slightly *less* deferred, not more.** A U is not a ramp: the")
    add("textbook trade-off assumes a back-loaded curve, and this one is")
    add("front-loaded too. The open auction at {:.2%} roughly offsets the close".format(
        prof.iloc[0]))
    add("at {:.2%}, so following the curve starts the order sooner as well as".format(
        prof.iloc[-1]))
    add("finishing it later. On this profile VWAP is better on impact and no")
    add("worse on timing, and the trade-off simply is not there.")
    add("")
    add("Where the trade-off *is* real is alpha. Neither schedule knows anything")
    add("about the next few hours; a signal that decays within the day is a")
    add("reason to trade faster than either, and the timing-exposure number")
    add("cannot see it because it prices dispersion rather than drift.")
    add("")

    add("## 5. The closing auction is not continuous trading")
    add("")
    add("| | share of the order landing in an auction bucket |")
    add("|---|---|")
    add("| TWAP | {:.2%} |".format(tw.auction_share))
    add("| VWAP | {:.2%} |".format(vw.auction_share))
    add("")
    add("The 15:55 bucket is {:.2%} of the day and is mostly the closing".format(
        prof.iloc[-1]))
    add("auction — a single price formed once, not continuous flow. *Submitting*")
    add("5% of the auction is a different act from *participating* at 5%: you")
    add("send an order in and find out what it printed at. Treating that bucket")
    add("as more of the same overstates how much of a schedule can actually be")
    add("placed there, which is why the share is flagged rather than folded into")
    add("the impact number.")
    add("")
    add("It also means VWAP's advantage is partly an accounting one. It earns")
    add("its lower impact by putting **{:.0%}** of the order into buckets it".format(
        vw.auction_share))
    add("cannot participate in the ordinary way.")
    add("")

    add("## What this still does not model")
    add("")
    add("- **60 days, 8 large caps.** Enough to measure the SHAPE, which is")
    add("  stable and well documented. Not enough to say anything about a")
    add("  particular day, an earnings date, an index rebalance, or a name that")
    add("  does not trade like these.")
    add("- **The curve is a forecast used as if it were known.** A real VWAP")
    add("  algo predicts today's volume and is wrong; the error is itself a cost")
    add("  and it is not modelled here.")
    add("- **No limit orders, no venue routing, no adverse selection.** Every")
    add("  slice is assumed to execute at the participation it asked for. A real")
    add("  schedule leaks information, and the fills that arrive most easily are")
    add("  the ones you least want.")
    add("- **No spread.** Impact here is the square-root term only. Crossing the")
    add("  spread on every slice is a separate cost that TWAP and VWAP pay")
    add("  differently, because they cross a different number of times.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "INTRADAY.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/INTRADAY.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
