"""Two books that pass every limit and are not remotely the same risk.

    python run_risk_model.py

`engine/risk.py` holds a MANDATE: caps per name, per sector, on gross and net.
Every one of those numbers is declared, and a mandate answers only "is this
position allowed?". It cannot answer "how much can this book lose, and from
what?" -- that needs a covariance matrix, which needs data.

This runs both on the real cached prices (8 US large caps, 2015-2024) and shows
the gap directly: two books, identical gross, identical net, both inside every
limit, and one of them carries far more risk than the other. The mandate sees no
difference. The risk model sees all of it.

Writes docs/RISK_MODEL.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from engine.risk import RiskLimits, apply_limits, exposures
from engine.risk_model import condition_number, estimate, shrunk_covariance

CACHE = ROOT / "data" / "prices.parquet"

# Sectors for the cached names. Used by the mandate, ignored by the covariance
# -- which is itself part of the point: a sector label is someone's opinion
# about what moves together, and the correlation matrix is the measurement.
SECTORS = {"SPY": "index", "AAPL": "tech", "MSFT": "tech", "JNJ": "health",
           "XOM": "energy", "JPM": "financials", "PG": "staples",
           "KO": "staples"}


def _returns() -> pd.DataFrame:
    px = pd.read_parquet(CACHE)["close"]
    return px.pct_change().dropna()


def main() -> int:
    if not CACHE.exists():
        print("data/prices.parquet not found -- run run_real.py first")
        return 1

    rets = _returns()
    names = list(rets.columns)
    R = rets.to_numpy(float)

    limits = RiskLimits(max_name_weight=0.30, max_sector_weight=0.60,
                        max_gross=1.00, max_net=1.00)

    # Two books at the SAME gross and the SAME net.
    #   A: spread across sectors that move differently.
    #   B: concentrated in names that move together.
    book_a = {"JNJ": 0.25, "XOM": 0.25, "KO": 0.25, "JPM": 0.25}
    book_b = {"AAPL": 0.25, "MSFT": 0.25, "SPY": 0.25, "JPM": 0.25}

    L = []
    add = L.append
    add("# ML-2 — a risk model estimated from data, next to the mandate")
    add("")
    add("Generated by `run_risk_model.py` on the real cached prices")
    add("(8 US large caps, {} trading days, {}–{}).".format(
        len(rets), rets.index[0].date(), rets.index[-1].date()))
    add("")
    add("`engine/risk.py` holds a **mandate**: caps per name, per sector, on")
    add("gross and net. Every one of those numbers is a declared input, so it")
    add("answers `is this position allowed?` and nothing else. `how much can")
    add("this book lose, and from what?` is a different question and it needs a")
    add("covariance matrix.")
    add("")

    add("## 1. Two books the mandate cannot tell apart")
    add("")
    rows = []
    for label, book in (("A (spread across sectors)", book_a),
                        ("B (tech + index + a bank)", book_b)):
        _, bound = apply_limits(book, SECTORS, limits)
        exp = exposures(book, SECTORS)
        est = estimate(R, book, names)
        rows.append((label, book, exp, est, bound))

    add("| book | positions | gross | net | limits that bound |")
    add("|---|---|---|---|---|")
    for label, book, exp, _, bound in rows:
        add("| {} | {} | {:.2f} | {:+.2f} | {} |".format(
            label, ", ".join(book), exp["gross"], exp["net"],
            ", ".join(bound) if bound else "none — both fully compliant"))
    add("")
    add("Same gross, same net, same position count, four names each, every")
    add("limit satisfied. **The mandate reports these as equivalent.**")
    add("")

    add("## 2. What the covariance says about them")
    add("")
    add("| | book A | book B |")
    add("|---|---|---|")
    a, b = rows[0][3], rows[1][3]
    add("| annualised volatility | {:.2%} | {:.2%} |".format(
        a.volatility_annual, b.volatility_annual))
    add("| parametric VaR 95% (daily) | {:.2%} | {:.2%} |".format(
        a.var_95, b.var_95))
    add("| parametric VaR 99% (daily) | {:.2%} | {:.2%} |".format(
        a.var_99, b.var_99))
    add("| diversification ratio | {:.3f} | {:.3f} |".format(
        a.diversification_ratio, b.diversification_ratio))
    add("")
    ratio = b.volatility_annual / a.volatility_annual
    add("Book B carries **{:.0f}% more volatility** than book A at identical".format(
        (ratio - 1) * 100))
    add("gross. Both hold four names; in B, AAPL, MSFT and SPY are substantially")
    add("the same exposure wearing three tickers. The diversification ratio is")
    add("what says so — the closer to 1.000, the more the book is one position.")
    add("")
    add("**There is no \"effective number of bets\" column here, and that is a")
    add("decision rather than an omission.** The standard entropy-over-principal-")
    add("components measure was implemented, measured, and rejected: it reads")
    add("1.004 at a pairwise correlation of 0.2, and every equity book shares a")
    add("market factor well above that, so it returns 1.0 for book A and 1.0 for")
    add("book B. `engine/risk_model.pca_effective_bets` keeps it next to the")
    add("tests that disqualified it. See §5.")
    add("")

    add("## 3. Which position is driving the risk")
    add("")
    add("| book | position | weight | risk share |")
    add("|---|---|---|---|")
    for label, book, _, est, _ in rows:
        held = {n: s for n, s in est.risk_contributions.items() if n in book}
        for n, share in sorted(held.items(), key=lambda kv: -kv[1]):
            add("| {} | {} | {:.0%} | {:.1%} |".format(
                label.split(" ")[0], n, book[n], share))
    add("")
    add("Every position is 25% of the book by weight and none of them is 25% of")
    add("the risk. That gap is the entire reason to decompose rather than sort")
    add("by size — **the largest position is almost never the largest risk**,")
    add("and a limits framework only ever sees the weight column.")
    add("")

    # ------------------------------------------------- why shrinkage
    add("## 4. Why the sample covariance is not good enough")
    add("")
    add("With N assets you estimate N(N+1)/2 parameters from T observations.")
    add("Below is the same estimate on the real returns and then on a wide,")
    add("short panel of the kind a real 60-name book actually has.")
    add("")
    add("| panel | assets | observations | parameters | condition number (sample) | (shrunk) |")
    add("|---|---|---|---|---|---|")
    for tag, sub in (("real prices, full history", R),
                     ("real prices, last 40 days", R[-40:])):
        n = sub.shape[1]
        s_cov = np.cov(sub, rowvar=False)
        sh_cov, intensity = shrunk_covariance(sub)
        add("| {} | {} | {} | {} | {:,.0f} | {:,.0f} |".format(
            tag, n, len(sub), n * (n + 1) // 2,
            condition_number(s_cov), condition_number(sh_cov)))

    rng = np.random.default_rng(0)
    for tag, T in (("60 names, 80 days (T > N)", 80),
                   ("60 names, 40 days (T < N)", 40)):
        wide = rng.normal(0, 0.01, size=(T, 60))
        s_cov = np.cov(wide, rowvar=False)
        sh_cov, intensity = shrunk_covariance(wide)
        add("| {} | 60 | {} | 1,830 | {:,.0f} | {:,.0f} |".format(
            tag, T, condition_number(s_cov), condition_number(sh_cov)))
    add("")
    add("**The threshold is T < N, not T < N(N+1)/2, and this originally said")
    add("otherwise.** At 60 names and 80 days the sample matrix is badly")
    add("conditioned but still full rank — it inverts. At 60 names and 40 days")
    add("it is *rank deficient*: at most 39 non-zero eigenvalues for 60 assets,")
    add("so 21 directions carry exactly zero estimated variance. An optimiser")
    add("does not fail on that. It reads those directions as riskless and puts")
    add("the whole book there, which is why \"minimum variance\" portfolios come")
    add("back holding enormous offsetting positions in two nearly identical")
    add("names.")
    add("")
    add("Ledoit-Wolf shrinkage pulls the estimate toward a constant-correlation")
    add("target at intensity **{:.3f}** on the rank-deficient panel, and restores".format(
        intensity))
    add("full rank. The result is biased on purpose, because a biased matrix you")
    add("can invert beats an unbiased one you cannot.")
    add("")

    add("## 5. A metric this rejected, and what rejected it")
    add("")
    add("Meucci's *effective number of bets* — entropy of the variance spread")
    add("over principal components — is the natural answer to \"how many")
    add("independent bets is this book?\", and three implementations were tried")
    add("before none of them was reported.")
    add("")
    add("| implementation | fails how |")
    add("|---|---|")
    add("| concentration of per-position risk contributions | an equal-weight book of three near-identical tech names has perfectly even contributions, so it scores well. On these prices it rated book B **above** book A — backwards. |")
    add("| entropy over principal components | exact on the *population* matrix (6.000 for six independent assets) and ~1.9 on a *sample* matrix of the same six with 4,000 observations. Near-equal eigenvalues make the eigenvectors an arbitrary rotation. |")
    add("| minimum-torsion (Löwdin) basis | fixes the independent case, then reports **two** effective bets for two perfectly correlated assets. Worse. |")
    add("")
    add("The disqualifying number is the second one's hair trigger: at pairwise")
    add("correlation **0.2 it already reads 1.004**. Every equity book shares a")
    add("market factor well above that, so it answers 1.0 for a diversified book")
    add("and 1.0 for a concentrated one. A number that gives the same answer to")
    add("both questions is not a measurement, so what gets reported is the crude")
    add("diversification ratio, which has no entropy in it and does move in the")
    add("right direction on real data. The rejected version stays in")
    add("`engine/risk_model.pca_effective_bets` beside the tests that killed it,")
    add("so it does not get re-added by the next person to have the idea.")
    add("")
    add("## 6. What this still does not buy")
    add("")
    add("- **Every number here is an estimate from history**, and history is the")
    add("  one sample where those correlations held. Correlations rise in a")
    add("  crisis — exactly when the figure matters — so a covariance-based risk")
    add("  number is a statement about calm markets that gets quoted during")
    add("  storms. Book A's diversification is measured on a decade in which")
    add("  energy and staples happened to diverge.")
    add("- **The VaR is parametric**, a normal quantile on the portfolio vol. It")
    add("  understates the tail on real returns, which are fat-tailed. It is")
    add("  labelled parametric everywhere it appears because calling it plain")
    add("  \"VaR\" is how a risk report becomes reassuring.")
    add("- **Eight names is not a risk model's natural habitat.** The")
    add("  conditioning problem this section is about barely bites at N=8; the")
    add("  60-name row is there because that is where it does, and this repo's")
    add("  cached universe cannot reach it with real data.")
    add("- **No factor model.** Decomposing risk into market, size, value and")
    add("  momentum is what a real risk system reports, and it needs factor")
    add("  returns this repo does not have.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "RISK_MODEL.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/RISK_MODEL.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
